hi: {
    accept: "स्वीकार  करें",
    acceptcredit: "धन स्वीकार करो",
    accounts: "हिसाब किताब",
    add: "जोड़ें",
    addcontact: "संपर्क जोड़ें",
    addfirsttransaction: "अपना पहला लेनदेन रिकॉर्ड करके प्रारंभ करें",
    addkathatransaction: "खाता लेन-देन जोड़ें",
    addnote: "टिप्पणी जोड़ें",
    address: "पता",
    addresscannotbeempty: "पता पंक्ति खाली नहीं हो सकती",
    addvoicememo: "वॉयस मेमो जोड़ें",
    agriculture: "कृषि",
    ageline: "आपकी उम्र ?",
    agelinetwo: "हमारी सेवा को बेहतर बनाने के लिए एक छोटा सर्वेक्षण!",
    alert: "चेतावनी",
    allowdownload: "कृपया डाउनलोड करने की अनुमति प्रदान करें!",
    alltransaction: "सभी लेन-देन",
    alreadyregistered: "पहले से रजिस्टर्ड ? ",
    amount: "रकम",
    amountrange: "राशि सीमा 1 - 99,999",
    amountterm: "राशि अवधि",
    amountdue: "देय राशि",
    amountowe: "बकाया राशि",
    amountowed: "बकाया राशि",
    amountowned: "स्वामित्व वाली राशि",
    appnotinstalled: "व्हाट्सएप इंस्टॉल नहीं है",
    appnottoast: "आपने ऐप इंस्टॉल नहीं किया",
    apply: "आवेदन करे",
    applyloan: "उधार के लिए आवेदन करे",
    areyouwanttogoback: "क्या आप वाकई वापस जाना चाहते हैं?",
    ascending: "आरोही",
    audio: "ऑडियो",
    audiopermalert: "कृपया ऑडियो रिकॉर्ड करने की अनुमति प्रदान करें!",
    audioplaytoast: "ऑडियो चल रहा है ...",
    audiounavailable: "ऑडियो उपलब्ध  नहीं है",
    authrequired: "प्रमाणीकरण की आवश्यकता है",
    availablebalance: "उपलब्ध शेष राशि",
    bankacctitle: "मेरा बैंक खाता",
    bankscreenmsg: "नीचे दीया गया लेन-देन इतिहास आपके एसएमएस अभिलेख पर आधारित है।",
    banksummary: "बैंक सारांश",
    bills: "बिल",
    calendar: "पंचांग",
    call: "कॉल करें",
    camera: "कैमरा",
    cancel: "रद्द करें",
    cash: "नकद",
    category: "वर्ग",
    changelanguage: "भाषा बदलो",
    changeprofilepicture: "प्रोफ़ाइल चित्र बदलें",
    checkbankbalance: "चेक बैंक बैलेंस",
    checkbankbalancetoast: "कृपया जारी रखने के लिए आवश्यक अनुमति प्रदान करें !!",
    checkyourbalance: "अपने बैंक बैलेंस की जाँच करें",
    choosenumber: "नंबर चुनें",
    chooselanguage: "जारी रखने के लिए भाषा चुनें",
    clearfilter: "फिल्टर हटाए",
    clipboardtoast: "क्लिपबोर्ड में कॉपी की गई राशि",
    close: "बंद करे",
    confirmbutton: "पुष्टि करें",
    confirmlogout: "लॉगआउट की पुष्टि करें",
    confirmpassword: "अपने पासवर्ड की पुष्टि करें",
    confirmpattern: "पैटर्न की पुष्टि करें",
    confirmpatternmsg: "कृपया पुष्टि करने के लिए पैटर्न को फिर से ड्रा करें",
    confirmpin: "पिन की पुष्टि करें",
    contactnotfound: "संपर्क नहीं मिला",
    contactpermission: "कृपया संपर्क जोड़ने के लिए संपर्क अनुमति स्वीकार करें",
    contacts: "संपर्क",
    credit: "श्रेय",
    creditgiven: "उधार दिया",
    credittaken: "उधार लिया",
    dashboard: "मुख्य पृष्ठ",
    date: "तारीख",
    daterange: "तिथि सीमा",
    daterangefilter: "फ़िल्टर करने के लिए दिनांक सीमा का चयन करें",
    delete: "हटाएँ",
    deletionsuccessful: "डिलीट कर दिया गया है...",
    deletetoast: "डिलीट ट्रांजैक्शन",
    deletetoasttwo: "क्या आप वाकई इस लेन-देन को हटाना चाहते हैं ?",
    delivered: "मैसेज पहुंचा दिया गया",
    description: "विवरण",
    descending: "उतरते",
    download: "डाउनलोड",
    enddate: "अंतिम तिथि",
    email: "ईमेल",
    enterpinmsg: "4 अंकों का पिन डालें",
    enterreceivervpn: "UPI प्राप्त करें दर्ज करें",
    entervalidemail: "मान्य ईमेल पता दर्ज करें",
    entervalidphonenumber: "कृपया एक वैद्य नंबर डालें",
    errorboundarymsg: "वो आप नहीं हैं। ये हम हैं। कृपया इसे एक और कोशिश दें.",
    exitjandhan: "जंडन से बाहर निकलें",
    exitlinetwo: "क्या आप ऐप से बाहर निकलना चाहते हैं ?",
    errornote: "कुछ त्रुटि हुई",
    expenses: "आपके खर्चे",
    features: "विशेषताएं",
    filedownloaded: "आपकी फ़ाइल डाउनलोड हो गई",
    filterchatbydate: "फ़िल्टर चैट दिनांक तक",
    filters: "फिल्टर",
    fingerprint: "अंगुली की छाप",
    firstname: "पहला नाम",
    firstnamecannotbeempty: "पहला नाम खाली नहीं हो सकता",
    forgotpassword: "पासवर्ड भूल गए",
    from: "तारीख से",
    gallery: "गेलरी",
    getstartedwith: "शुरू करें",
    give: "उधार दें",
    givecredit: "पैसे दो",
    giveto: "देना",
    governtmentschemes: "सरकारी योजनाएं",
    grocery: "किराना",
    help: "सहायता",
    indev: "विकास में",
    influencerpoints: "इन्फ्लुएंसर अंक",
    inneedhelpusingjandhan: "मुझे जनधन का उपयोग करने में मदद चाहिए",
    inputpatternmsg: "इनपुट पैटर्न",
    insurance: "बीमा",
    internetconnection: "कृपया अपने इंटरनेट कनेक्शन की जाँच करें",
    invalidamount: "अमान्य राशि",
    invalidcredentials: "अमान्य क्रेडेंशियल्स",
    invalidotp: "अमान्य ओटीपी",
    jandhan: "जनधन",
    keeptrackdues: "अपने बकाए का ध्यान रखें",
    khatasummary: "खता सारांश",
    lastname: "उपनाम",
    lastnamecannotbeempty: "उपनाम  रिक्त नहीं हो सकता",
    ledger: "बही खाता",
    lessthan18: "18 से कम",
    listeningtoast: "सुनकर .....",
    loan: "ऋण",
    login: "लॉग इन",
    loginhere: "यहां लॉगिन करें",
    logout: "लोग आउट",
    logoutmessage: "क्या आप लॉग आउट करना चाहते हैं",
    makeandreceivepayments: "पेमेंट्स भेजें और रिसीव करें",
    makepayment: "भुगतान करो",
    maxsixdigits: "अधिकतम 6 अंक की अनुमति है",
    moreinfo: "More Information",
    mobilenoplaceholder: "आगे बढ़ने के लिए अपना मोबाइल नंबर दर्ज करें",
    more: "अधिक",
    mydocuments: "मेरे दस्तावेज",
    mydocumentsinfo:
     "साझा करने के लिए अपना पहला डूमेंट अपलोड करके प्रारंभ करें।",
    name: "नाम",
    netbalance: "शेष बैलेंस",
    newpatternmsg: "नया पैटर्न डालिये",
    no: "नहीं",
    noappmsg: "UPI सपोर्ट के साथ कोई ऐप नहीं मिला !!",
    none: "कुछ भी नहीं",
    nonotifications: "अभी तक कोई नई सूचना नहीं",
    nonumbertoast: "इस संख्या के साथ कोई खाता मौजूद नहीं है",
    notes: "टिप्पणियाँ",
    notransaction: "कोई परिणाम नहीं मिले",
    norecords: "कोई रिकॉर्ड नहीं मिला",
    nonumberfound: "संपर्क नंबर खाली है",
    nointernetconnection: 'कोई इंटरनेट कनेक्शन नहीं',
    ok: "ठीक",
    otp: "OTP",
    oops: "उफ़!",
    open: "खोले",
    over: "60 से अधिक",
    otpincorrect: "ओ.टी.पी. गलत",
    otpmessage: "ओ.टी.पी. प्राप्त नहीं किया है?",
    otpverification: "ओ.टी.पी. सत्यापन",
    otpscreenmsg: "6 अंक ओ.टी.पी. आपके पंजीकृत मोबाइल नंबर पर भेजा गया है",
    owesyou: "आप प्राप्त करने वाले हैं",
    password: "ओ.टी.पी",
    passwordcorrect: "पासवर्ड सही",
    passwordcannotbeempty: "पासवर्ड खाली नहीं हो सकता",
    passwordnotsame: "पासवर्ड समान नहीं है",
    passwordnotmatch: "पासवर्ड नही मिल रहा",
    passwordsuccessmessage: "पासवर्ड सफलतापूर्वक सेट करें",
    pattern: "पैटर्न",
    payment: "भुगतान",
    paymentamount: "भुगतान राशि",
    paymentmode: "भुगतान का तरीका",
    permissiontoast: "कृपया जारी रखने के लिए अनुमति दें !!",
    phone: "फ़ोन नंबर",
    phonenumber: "मोबाइल नंबर",
    pin: "पिन",
    pleasereenter: "कृपया पुष्टि करने के लिए 4 अंकों का पिन फिर से दर्ज करें",
    printstatement: "स्टेटमेंट प्रिंट करें",
    proceed: "बढ़ना",
    profile: "प्रोफ़ाइल",
    profiletoast: "प्रोफ़ाइल अपडेट सफलतापूर्वक ...",
    recent: "हाल का",
    referandearn: "शेयर करें और कमाएँ",
    register: "रजिस्टर",
    remove: "हटाना",
    resend: "पुन: भेजें",
    restart: "पुनर्प्रारंभ करें",
    remaindernote: "शेष भेजा गया",
    resetpassword: "पासवर्ड रीसेट",
    restartinternetapp: 'इंटरनेट कनेक्शन के साथ ऐप को पुनरारंभ करें',
    save: "अपडेट करें",
    savedtoast: "सेविंग .... प्लीज वेट",
    screenonetext: "डिजिटल उधार खता (लेजर) आपके फोन पर",
    screenthreetext: "भारत सरकार की योजनाओं का लाभ उठाएं",
    settings: "समायोजन",
    searchby: "द्वारा खोज",
    searchByName: "नाम, राशि या लेनदेन नोट…।",
    searchcontact: "संपर्क खोजें",
    searchhere: "यहाँ ढूँढे",
    selectoccupation: "कृपया अपने व्यवसाय का चयन करें!",
    security: "सुरक्षा",
    securitytoast: "कृपया रीसेट करने के लिए एक वैध सुरक्षा विकल्प चुनें",
    sendministatement: "मिनी स्टेटमेंट भेजें",
    sendnotificaton: "अधिसूचना भेजें",
    sendremainder: "याद दिलाना",
    settings: "सेटिंग्स",
    share: "शेयर करें",
    sharejandhan: "शेयर करें जनधन ऐप",
    sharelinkverb: "अपने फोन पर उधार खाता डाउनलोड करें। सरकार की योजनाओं का उपयोग करें। जन धन ऐप को आमंत्रित लिंक के साथ डाउनलोड करें: ",
    sharepermission: "कृपया शेयर करने की अनुमति दें / डाउनलोड",
    sharefb:"शेयर फेसबुक",
    shareinfo:"जानकारी शेयर करें",
    shareinvitecode:"शेयर कोड आमंत्रित करें ",
    sharevia: "शेयर करने का माध्यम",
    sharewith: "शेयर करें",
    sharewithfamily: "इसे अपने दोस्तों और परिवार के साथ शेयर करें!",
    signupwithphone: "फोन से साइन अप करें",
    skip: "छोड़ें",
    sms: "एसएमएस",
    smsheading: "चलो शुरू करें",
    smslinefour: "जन धन आपके एसएमएस के आधार पर आपके खर्च और बिल का आयोजन करता है।",
    smslinethree: "जन धन आपके एसएमएस के आधार पर आपके खर्च और बिल का आयोजन करता है।",
    smslinetwo: "जन धन एसएमएस की पहुँच की आवश्यकता है",
    submit: "सबमिट करें",
    supportandfeedback: "समर्थन और प्रतिक्रिया",
    startdate: "आरंभ करने की तिथि",
    steptwo: "चरण 2",
    surveytag: "हमारी सेवा में सुधार के लिए एक छोटा सर्वेक्षण!",
    to: "तारीख तक",
    today: "आज",
    tokeepinfo: "अपनी जानकारी को सुरक्षित रखने के लिए",
    totalamount: "कुल रकम",
    totalbalance: "कुल शेष",
    transactionby: "द्वारा लेनदेन",
    transactionmake: "बनायें",
    transactionpayment: "भुगतान",
    transactionrequest: "निवेदन",
    transactionstatemant: "लेन-देन बयान",
    updatefield: "कृपया मान्य फ़ील्ड दर्ज करें",
    upload: "अपलोड",
    uploading: "अपलोड...",
    uploadpictures: "चित्र अपलोड करें",
    uploadprofilepicture: "प्रोफ़ाइल चित्र अपलोड करें",
    useralreadyexist: "इस फोन के साथ उपयोगकर्ता पहले से मौजूद है",
    validamoutmessage: "कृपया मान्य राशि दर्ज करें",
    verifyphone: "फ़ोन सत्यापित करें",
    visitwebsite: "बेवसाइट देखना",
    vpa: "UPI",
    vieworupload: "दस्तावेज़ देखें / अपलोड करें",
    vpacannotbeempty: "UPI खाली नहीं हो सकता",
    welcomenoteone: "में स्वागत",
    welcomenotetwo: "जन धन ऐप",
    whatisthisfor: "यह किस लिए है ?",
    whatsapp: "व्हाट्सएप",
    whatsappnotinstalled: "व्हाट्सएप इंस्टॉल नहीं",
    whatsappsupport: "कृपया हमें अपनी चिंताओं के बारे में बताएं, हम जल्द ही आपसे संपर्क करेंगे",
    whatsappus: "व्हाट्सएप करो",
    wronginputpassword: "गलत पासवर्ड, फिर से प्रयास करें",
    yes: "हाँ",
    yougavecredit: "आप श्रेय देते हैं",
    youowe: "आपके द्वारा देय हैं",
    yourcoins: "आपके सिक्के",
    youreceivedcredit: "आपको श्रेय मिला",
    yourreferralcode: "आपका रेफरल कोड",
    youroccupation: "आपका व्यवसाय ?"
  },



  